base_model: NousResearch/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

dataloader_num_workers: 8

max_grad_norm: 0.8


load_in_8bit: false
load_in_4bit: true
strict: false

chat_template: llama3
datasets:
dataset_prepared_path:
val_set_size: 0.0
output_dir: miner_id_24_lowloss

sequence_len: 1024
sample_packing: false
pad_to_sequence_len: true
trust_remote_code: true

adapter: lora
lora_model_dir:
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
lora_target_linear: true
lora_fan_in_fan_out:

loraplus_lr_embedding: 1.0e-06
loraplus_lr_ratio: 16

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 5

optimizer: adamw_bnb_8bit

lr_scheduler: cosine_with_restarts
learning_rate: 0.00008

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience: 3
eval_steps: 200
save_steps: 300


resume_from_checkpoint:
local_rank:
logging_steps:
xformers_attention:
flash_attention: true
s2_attention:

wandb_project: Gradients-On-Demand
wandb_entity:
wandb_mode: offline
wandb_run: your_name
wandb_runid: default

hub_model_id:
hub_repo:
hub_strategy: checkpoint
hub_token:


saves_per_epoch: 2
save_total_limit: 5
warmup_steps: 150
evals_per_epoch: 4
eval_table_size: 64
eval_max_new_tokens: 128
max_steps: 1500
debug: false
deepspeed: auto
weight_decay: 0.0
fsdp: full_shard
fsdp_config:
